repository: i-Navi/i-Navi
repository_url: https://github.com/i-Navi/i-navi.GitHub.io

timezone: Asia/Shanghai
lang: zh_CN

title: 网站导航 · i-Navi
alias_en: i-Navi
alias_cn: 网站导航
description: 我的网站导航
keywords: 网站导航, i-Navi, BYR, BUPT, Navi, Navigation
url: https://i-navi.github.io/
established_at: "2016-10-01T00:00+08:00"

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-dark.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
